### ISSUE TITLE
can't hear master - requires tidal desktop etc

### ISSUE THREAD

**Issue by arielhai** [rippin93/tidal-desktop#10]
did all that:
tar xf tidal_desktop-vX.Y.Z.tar.xz
chown -R 1000:1000 release
cd release
./deploy.sh

and then run it and it still shows i don't have desktop version and can't run master 
ubuntu 20.04

**Comment by mhoangvslev** [comment]
This is not an official release approved by tidal. This is just an electron app with tidal web in it.

**Comment by rippin93** [comment]
It's an electron app which I wrote for myself to get any "application"-like feature for linux. Baseline it's just https://listen.tidal.com
